default: &default
  adapter: postgresql
  encoding: unicode
  pool: 5
  username: postgres
  password: postgres

development:
  <<: *default
  database: active_react_app_development
test:
  <<: *default
  database: active_react_app_test

production:
  <<: *default
  database: active_react_app_production
  username: postgres
  password: postgres
